# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('plate_appearances', models.IntegerField(default=0)),
                ('at_bats', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('walks', models.IntegerField(default=0)),
                ('hit_by_pitch', models.IntegerField(default=0)),
                ('sacrifice_flies', models.IntegerField(default=0)),
                ('sacrifice_hits', models.IntegerField(default=0)),
                ('singles', models.IntegerField(default=0)),
                ('doubles', models.IntegerField(default=0)),
                ('triples', models.IntegerField(default=0)),
                ('home_runs', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pitcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('batters_faced', models.IntegerField(default=0)),
                ('hits_allowed', models.IntegerField(default=0)),
                ('walks_allowed', models.IntegerField(default=0)),
                ('hit_by_pitches_allowed', models.IntegerField(default=0)),
                ('home_runs_allowed', models.IntegerField(default=0)),
            ],
        ),
    ]
